### ISSUE TITLE
cargo install tmtc-c2a --git が失敗する

### ISSUE THREAD

**Issue by kobkaz** [arkedge/gaia#202]
`cargo install tmtc-c2a --git https://github.com/arkedge/gaia` が以下のエラーで失敗する

> package \`(略)/devtools-frontend/crates/opslang-wasm/Cargo.toml` is a member of the wrong workspace

**Comment by kobkaz** [comment]
有識者 @sksat

**Comment by sksat** [comment]
これダメなのか............

**Comment by shunsuke-shimomura** [comment]
同じか分からないのでとりあえずここに書くのですが、まっさらなworkspaceのCargo.tomlに以下のように書いてcargo buildしたところ、エラーを吐かれました。
``` Cargo.toml
[dependencies]
gaia-stub = { git = "https://github.com/arkedge/gaia.git", tag = "v1.0.0" }
gaia-tmtc = { git = "https://github.com/arkedge/gaia.git", tag = "v1.0.0" }
gaia-ccsds-c2a = { git = "https://github.com/arkedge/gaia.git", tag = "v1.0.0" }
tmtc-c2a = { git = "https://github.com/arkedge/gaia.git", tag = "v1.0.0" }
```

``` zsh
error: failed to run custom build command for `opslang-wasm v1.0.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/shimomura/issl/comm_gs/onglaisat-gs-proxy/target/debug/build/opslang-wasm-e58b17e55e40eb7f/build-script-build` (exit status: 101)
  --- stdout
  cargo:out_dir=/home/shimomura/issl/comm_gs/onglaisat-gs-proxy/target/debug/build/opslang-wasm-4e87403ccaf7b971/out

  --- stderr
  thread 'main' panicked at /home/shimomura/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opslang-wasm-1.0.0/build.rs:37:10:
  failed to execute wasm-pack: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
     2: core::result::unwrap_failed
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
     3: core::result::Result<T,E>::expect
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```

試しにv0.6.1にしたら通りました
